export const STATUS = {
    NONE: 'NONE',
    LOADING: 'LOADING',
    SUCCESS: 'SUCCESS',
    FAILURE: 'FAILURE',
}
//status
export const GET_PRODUCTS_ATTEMPT = 'GET_PRODUCTS_ATTEMPT';
export const GET_PRODUCTS_SUCCEES = 'GET_PRODUCTS_SUCCEES';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

export const GET_PRODUCT_NONE = 'GET_PRODUCT_NONE';
export const GET_PRODUCT_ATTEMPT = 'GET_PRODUCT_ATTEMPT';
export const GET_PRODUCT_SUCCEES = 'GET_PRODUCT_SUCCEES';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

//products
export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART';
export const DELETE_PRODUCT_CART = 'DELETE_PRODUCT_CART';
export const BUY_PRODUCTS_ATTEMPT = 'BUY_PRODUCTS_ATTEMPT';
export const BUY_PRODUCTS_SUCCESS = 'BUY_PRODUCTS_SUCCESS';
export const BUY_PRODUCTS_FAILURE = 'BUY_PRODUCTS_FAILURE';
//cart
export const CHANGE_THEME_APP = 'CHANGE_THEME_APP';
//theme
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';
// export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';
//auth